### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by MK3D2024** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#61]
i get this error while using via console 

Microsoft Windows [Version 10.0.22631.2715]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>python C:\ArcOverhangs\prusa_slicer_post_processing_script.py C:\ArcOverhangs\1.gcode
Traceback (most recent call last):
  File "C:\ArcOverhangs\prusa_slicer_post_processing_script.py", line 840, in <module>
    class BridgeInfill():
  File "C:\ArcOverhangs\prusa_slicer_post_processing_script.py", line 841, in BridgeInfill
    def __init__(self,pts=[],id=random.randint(1,1e10)) -> None:
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kareem Salama\AppData\Local\Programs\Python\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kareem Salama\AppData\Local\Programs\Python\Python312\Lib\random.py", line 312, in randrange
    istop = _index(stop)
            ^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

C:\Windows\System32>python C:\ArcOverhangs\prusa_slicer_post_processing_script.py C:\ArcOverhangs\1.gcode
Traceback (most recent call last):
  File "C:\ArcOverhangs\prusa_slicer_post_processing_script.py", line 840, in <module>
    class BridgeInfill():
  File "C:\ArcOverhangs\prusa_slicer_post_processing_script.py", line 841, in BridgeInfill
    def __init__(self,pts=[],id=random.randint(1,1e10)) -> None:
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kareem Salama\AppData\Local\Programs\Python\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kareem Salama\AppData\Local\Programs\Python\Python312\Lib\random.py", line 312, in randrange
    istop = _index(stop)
            ^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

and while using inside slicer i get this error

![image](https://github.com/nicolai-wachenschwan/arc-overhang-prusaslicer-integration/assets/151872707/f2890858-d806-4f41-97e8-8d8cca5a7525)

![Screenshot 2023-11-23 204357](https://github.com/nicolai-wachenschwan/arc-overhang-prusaslicer-integration/assets/151872707/26b2be21-d4e3-4777-85e7-81c5a1a390da)
![Screenshot 2023-11-23 204535](https://github.com/nicolai-wachenschwan/arc-overhang-prusaslicer-integration/assets/151872707/88004428-7aad-4290-a6ab-09578f8c8455)

**Comment by gvancamp** [comment]
I'm getting the same error.

**Comment by MrBarbie** [comment]
I believe this is the error #60 suggested a fix for. In my case the edit suggested resolved the issue

**Comment by nicolai-wachenschwan** [comment]
sorry it took so long, is fixed now!
