### ISSUE TITLE
EOFError: EOF when reading a line  -- > line 1197 and line 109 

### ISSUE THREAD

**Issue by cmadson** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#68]
I am receiving this error when exporting out of PrusaSlicer as a post processing script or when running standalone. 

Post-processing script /usr/bin/python3 /Users/cm/scripts/prusa_slicer_post_processing_script.py on file /var/folders/mb/6fmyt45x6fd0ntcxhh9yg7880000gp/T/.94609.gcode.pp failed.
Error code: 1
Output:
Traceback (most recent call last):
File "/Users/cm/scripts/prusa_slicer_post_processing_script.py", line 1197, in 
main(gCodeFileStream,path2GCode, skipInput)
File "/Users/cm/scripts/prusa_slicer_post_processing_script.py", line 109, in main
input("Can not run script, gcode unmodified. Press enter to close.")
EOFError: EOF when reading a line

// system info
macOS 14.2.1
-rwxrwxrwx@  1 cm              staff  64019 Jan 27 10:33 prusa_slicer_post_processing_script.py

Python 3.11.7 (main, Jan  1 2024, 01:39:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin

>>pip list
Package             Version
------------------- -------
altgraph            0.17.2
contourpy           1.2.0
cycler              0.12.1
fonttools           4.47.2
future              0.18.2
importlib-resources 6.1.1
kiwisolver          1.4.5
macholib            1.15.2
matplotlib          3.8.2
numpy               1.26.3
numpy-hilbert-curve 1.0.1
packaging           23.2
pillow              10.2.0
pip                 23.3.2
pyparsing           3.1.1
python-dateutil     2.8.2
setuptools          58.0.4
shapely             2.0.2
six                 1.15.0
wheel               0.37.0
zipp                3.17.0

**Comment by cmadson** [comment]
Oh and thank you for writing this!

**Comment by cmadson** [comment]
Not sure when happened, while helping another user on here with their logged issue (non standard ascii characters in gcode) I installed python 3.9.18 and pyenv to reset my env.  Now your script runs great with both his original file including the weird characters as well as the cleaned up version.
